export const USER_PATHS = {
  home: "/user",
  profile: "/user/profile",
  bookings: "/user/bookings",
  reliability: "/user/reliability",
  saved: "/user/saved",
  notifications: "/user/notifications",
  review: (bookingId: string): string => `/user/bookings/${bookingId}/review`,
  hotels: "/user/hotels",
  restaurants: "/user/restaurants",
  trips: "/user/trips",
  events: "/user/events",
  guides: "/user/guides",
  attractions: "/user/attractions",
} as const;
